name: Deploy Backend

on:
    push:
        paths:
            - 'apps/backend/*'
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: SSH and Deploy
            env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            run: |
                echo "$SSH_PRIVATE_KEY" >> keyfile
                chmod 600 keyfile
                mkdir -p ~/.ssh/known_hosts
                ssh -t -i keyfile ubuntu@ec2-13-51-174-175.eu-north-1.compute.amazonaws.com "sudo bash /home/ubuntu/codes-era_monorepo/apps/backend/deploy.sh"