
name: Deploy Client Next

on:
  push:
    paths:
      - 'apps/frontend-nextapp/**'
      # - 'packages/ui/**'
      # - 'packages/common/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-16-171-129-151.eu-north-1.compute.amazonaws.com "sudo bash /home/ubuntu/codes-era_monorepo/Dockerized-Monorepo-of-codesera/apps/backend/deploy.sh"
